name: adcirc-plot
channels:
  - defaults
dependencies:
  - sphinx-gallery
  - mo_pack
  - sphinx_rtd_theme
  - graphviz
  - pip
  - matplotlib
  - nc-time-axis
  - imagehash[version='>=4.0']
  - python-stratify
  - cartopy[version='>=0.18']
  - black=20.8b1
  - pyke
  - sphinx
  - pyugrid
  - pre-commit
  - cftime[version='<1.3.0']
  - scipy
  - numpy[version='>=1.14']
  - pillow[version='<7']
  - filelock
  - asv
  - flake8
  - cf-units[version='>=2']
  - nose
  - dask[version='>=2']
  - esmpy[version='>=7.0']
  - python-xxhash
  - python=3.8
  - pandas
  - sphinx-copybutton
  - sphinxcontrib-napoleon
  - setuptools[version='>=40.8.0']
  - sphinx-panels
  - netcdf4
  - iris-sample-data
  - requests
  - ipython